### ISSUE TITLE
Request!

### ISSUE THREAD

**Issue by Rachit-Gandhi** [atahanoezer/Wind#1]
Hey!
Can I use snippets of the code you have here to preprocess data and co-work on the data. I am trying for power prediction, no blind copying will be done and you will be credited ofcourse!

**Comment by atahanoezer** [comment]
Hey Rachit,
I forgot to add a license but it will be a MIT license. That means you can use it in any form ( Except if you taking the MLSES course in Uni Tuebingen ) but be aware that the current status of the project is quite immature, and you might encounter many bugs. There will be a significant update for the second deadline of the project around mid of August.

**Comment by Rachit-Gandhi** [comment]
thanks @atahanoezer is there a way to contact you, to discuss the project and work on improvements, I have been assigned this project as an assignment in Internship in a strict deadline manner for August end and am working on multiple environment seem unknown, we could discuss and maybe share notes across domains, to be beneficial to both and ofcourse I am not in MLSES Course at specified Uni, I will also update my repo, Improvements till now are in Data Preprocessing domain and wrapping entire project in Darts, for more cleanliness in code. Also i will be implementing few naive models and ml methods as base line and work to go for more deep learning focused approach, Also just realised my message may come off pushy please feel free to reject the proposal according to your comfort. Anyways Thanks for the correspondence.

**Comment by Rachit-Gandhi** [comment]
Hey @atahanoezer , just an update for you, XGB works great for feature selections

**Comment by atahanoezer** [comment]
Hey @Rachit-Gandhi, the project is much more mature now. You can directly use datasets via Google Colab. Also, feature selection and hyperparameter optimization are available with the latest version.

**Comment by Rachit-Gandhi** [comment]
Hey @atahanoezer , just did a brief overview, seems great I will check it in detail in a few months, thanks for the details, you are welcome to try  out my [wind-power-time-series](https://github.com/Rachit-Gandhi/wind_power_time_series/tree/new_organised) repo, the updated branch is organised but maybe not runnable directly as more documentation is needed, I had a 2 months deadline on my project, requiring me to speed up the process, your initial analysis helped a lot. My proposed model was Ensemble CNN-LSTM with attention, with tabnet and xgboost for feature importance. If you ever pursue this project more formally please reach out
